/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ayush
 */
public class Select extends javax.swing.JFrame {

    /**
     * Creates new form Select
     */
    public Select() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        ADD = new javax.swing.JRadioButton();
        VIEW = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        profile = new javax.swing.JRadioButton();
        tr = new javax.swing.JRadioButton();
        BUY = new javax.swing.JRadioButton();
        LIBRARY = new javax.swing.JRadioButton();
        OUT = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 255, 255));
        jTextField1.setText("MOVIE LOG DASHBOARD");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 454, 76));

        ADD.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        getContentPane().add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 188, 55));

        VIEW.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        VIEW.setText("VIEW");
        VIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWActionPerformed(evt);
            }
        });
        getContentPane().add(VIEW, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 137, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Keep track of all your movie in a single place!!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 614, 108));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 255));
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 304, -1));

        jLabel1.setText("______________________________________________________________________________________________________");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 530, -1));

        profile.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        profile.setText("View Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 20));

        tr.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tr.setText("View Trend");
        tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trActionPerformed(evt);
            }
        });
        getContentPane().add(tr, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        BUY.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BUY.setText("BUY MOVIE");
        BUY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUYActionPerformed(evt);
            }
        });
        getContentPane().add(BUY, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        LIBRARY.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LIBRARY.setText("LIBRARY");
        LIBRARY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIBRARYActionPerformed(evt);
            }
        });
        getContentPane().add(LIBRARY, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        OUT.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        OUT.setText("LOG OUT");
        OUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OUTActionPerformed(evt);
            }
        });
        getContentPane().add(OUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
         if(ADD.isSelected()){
            
        
            setVisible (false);
            add obj= new add();
            obj.setVisible ( true);        // TODO add your handling code here:
    }// TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    private void VIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWActionPerformed
if(VIEW.isSelected()){
            
        
            setVisible (false);
            view obj= new view();
            obj.setVisible ( true); 
                // TODO add your handling code here:
    }           // TODO add your handling code here:
    }//GEN-LAST:event_VIEWActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
         if(profile.isSelected()){
            
        
            setVisible (false);
           Profile obj= new Profile();
            obj.setVisible ( true);        // TODO add your handling code here:
    }        // TODO add your handling code here:
    }//GEN-LAST:event_profileActionPerformed

    private void trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trActionPerformed
if(tr.isSelected()){
            
        
            setVisible (false);
            STATS obj= new STATS();
            obj.setVisible ( true); 
                // TODO add your handling code here:
    }           // TODO add your handling code here:
           // TODO add your handling code here:
    }//GEN-LAST:event_trActionPerformed

    private void BUYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUYActionPerformed
    if(BUY.isSelected()){
            
        
            setVisible (false);
            buy obj= new buy();
            obj.setVisible ( true); 
                // TODO add your handling code here:
    }        // TODO add your handling code here:
        // TODO add your handling code here:
    // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_BUYActionPerformed

    private void LIBRARYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIBRARYActionPerformed
        if(LIBRARY.isSelected()){
            
        
            setVisible (false);
            LIBRARY_PAGE obj= new LIBRARY_PAGE();
            obj.setVisible ( true); 
                // TODO add your handling code here:
    } // TODO add your handling code here:
    }//GEN-LAST:event_LIBRARYActionPerformed

    private void OUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OUTActionPerformed
       if(OUT.isSelected()){
            
        
            setVisible (false);
            LOGINpage obj= new LOGINpage();
            obj.setVisible ( true); 
                // TODO add your handling code here:
    } // TODO add your handling code here:
    }//GEN-LAST:event_OUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ADD;
    private javax.swing.JRadioButton BUY;
    private javax.swing.JRadioButton LIBRARY;
    private javax.swing.JRadioButton OUT;
    private javax.swing.JRadioButton VIEW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton profile;
    private javax.swing.JRadioButton tr;
    // End of variables declaration//GEN-END:variables
}
